#!/usr/bin/env python3
"""Prepare the Codex10k Gmail draft queue lead data."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "draft-batch-leads.json"


def support_lead(
    *,
    lead_id: str,
    buyer: str,
    email: str,
    subject: str,
    source_url: str,
    opportunity: str,
    title: str,
    price: int,
    segment: str,
    visual: str,
    greeting: str,
    opening: str,
    fit: str,
    positioning: str,
    boundary: str,
    next_step: str,
    caution: str,
    deliverables: list[str],
    workflow: list[str],
    cc: str = "",
    exclusions: str = "This is not a full prime-vendor proposal unless the buyer confirms that path; it is a bounded support slice.",
    email_next_step: str | None = None,
    packet_path: str | None = None,
    pills: list[str] | None = None,
    reply_message_id: str = "",
) -> dict:
    return {
        "lead_id": lead_id,
        "buyer": buyer,
        "email": email,
        "cc": cc,
        "reply_message_id": reply_message_id,
        "subject": subject,
        "source_url": source_url,
        "opportunity": opportunity,
        "offer_title": title,
        "meta_description": f"A support packet for {buyer}: {title}.",
        "eyebrow": segment,
        "hero_title": title,
        "lede": positioning,
        "price_usd": price,
        "visual_asset": visual,
        "visual_alt": f"{segment} workflow visual with intake, QA, evidence, and handoff steps.",
        "workflow_steps": workflow[:5],
        "deliverables": deliverables[:6],
        "fit": fit,
        "positioning": positioning,
        "boundary": boundary,
        "next_step": next_step,
        "email_next_step": email_next_step or next_step,
        "exclusions": exclusions,
        "quote_note": "Fixed support slice, subject to buyer approval and the required response path.",
        "packet_path": packet_path or "Email-ready support packet; formal procurement rules still control if they apply.",
        "send_caution": caution,
        "greeting": greeting,
        "opening": opening,
        "pills": pills or [f"USD {price:,} fixed", "sample data first", "review before send"],
    }


COMMON_WEB_QA = [
    "Current-state crawl and risk register for priority pages, forms, documents, and integrations",
    "Accessibility, mobile, performance, SEO, analytics, and broken-link QA checklist",
    "Content migration sampling plan with redirects, metadata, and ownership notes",
    "Acceptance test scripts for staff review before launch or handoff",
    "Defect and retest tracker with severity, owner, and closeout evidence",
    "Launch-readiness memo with open risks, decision points, and next actions",
]

COMMON_DATA_QA = [
    "Requirements-to-acceptance matrix for the highest-risk workflow slice",
    "Sample-data mapping checklist with duplicate, missing-value, and exception rules",
    "Role-based UAT scripts with pass/fail evidence capture",
    "Issue and retest register with severity, owner, and closure criteria",
    "Reporting/export validation checklist for priority operational outputs",
    "Executive handoff memo with open risks and recommended next actions",
]

leads = [
    support_lead(
        lead_id="C10K-084",
        buyer="BakerRipley",
        email="abrown@bakerripley.org",
        subject="Eligibility note for RFP 26-06 Salesforce QA support",
        source_url="https://bakerripley.org/get-involved/become-a-vendor/",
        opportunity="RFP 26-06 Salesforce Professional Services",
        title="Salesforce implementation QA and UAT support sidecar",
        price=19500,
        segment="Salesforce services support",
        visual="assets/rrc-salesforce-qa-visual.png",
        greeting="Hi Ashley,",
        opening="I saw BakerRipley's RFP 26-06 for Salesforce Professional Services. Because the vendor conference appears to have been mandatory, I want to avoid an improper submission. I prepared a narrow QA/UAT support packet only for your review if this kind of support-sidecar is still eligible.",
        fit="The main RFP is for Salesforce professional services; the useful lane here is implementation QA, migration sampling, and UAT evidence beside a qualified Salesforce team.",
        positioning="I can support the implementation team with fixed-scope QA/UAT, release-readiness, and data-migration evidence without claiming to be a Salesforce prime.",
        boundary="No client, participant, or production CRM records should be sent by email; use dummy records or a secure BakerRipley-approved workspace.",
        next_step="Could you confirm whether a vendor without documented attendance at the May 5 mandatory conference may still be considered for a narrow support-sidecar role?",
        email_next_step="Could you confirm whether a vendor without documented attendance at the May 5 mandatory conference may still be considered for a narrow support-sidecar role? If not, no action is needed.",
        caution="Mandatory vendor conference risk. This draft asks eligibility before proposing work.",
        deliverables=COMMON_DATA_QA,
        workflow=["Process map", "Data sample", "UAT scripts", "Retest", "Release pack"],
        packet_path="Procedural eligibility note first; not a proposal submission unless BakerRipley confirms eligibility.",
        pills=["USD 19,500 fixed", "eligibility first", "Salesforce QA"],
    ),
    support_lead(
        lead_id="C10K-085",
        buyer="Connecticut Auditors of Public Accounts",
        email="Sandra.DeLaCruz@cga.ct.gov",
        cc="vincent.filippa@ctauditors.gov",
        subject="2026-01 APA SharePoint RFP subcontractor/support question",
        source_url="https://govtribe.com/opportunity/state-local-contract-opportunity/2026-01-apa-microsoft-sharepoint-maintenance-rfp-202601apa",
        opportunity="2026-01 APA Microsoft SharePoint Maintenance RFP",
        title="SharePoint workflow QA and maintenance support slice",
        price=12500,
        segment="SharePoint maintenance support",
        visual="assets/synergy-automation-workflow-visual.png",
        greeting="Hello Sandra,",
        opening="I am reviewing the 2026-01 APA Microsoft SharePoint Maintenance RFP and prepared a narrow SharePoint workflow-QA support packet. Before treating it as a response component, I wanted to ask the right procedural question.",
        fit="The RFP maps well to SharePoint workflow maintenance, permission review, template QA, and repeatable support evidence.",
        positioning="I can provide a fixed workflow-QA and maintenance-readiness slice either as a named specialist resource or beside the selected maintenance team.",
        boundary="No confidential audit files should be sent by email; the first pass can use site structure, redacted examples, or dummy records.",
        next_step="May respondents include named subcontractors or specialist partner resources for SharePoint/Power Platform maintenance, and where should those roles and qualifications be described?",
        caution="Email is appropriate, but Sandra is the inquiry contact; proposal/submission goes to Vincent.",
        deliverables=COMMON_DATA_QA,
        workflow=["Inventory", "Permissions", "Flow checks", "Template QA", "Maintenance log"],
        packet_path="Formal RFP question to inquiry contact; proposal path remains controlled by the RFP.",
        pills=["USD 12,500 fixed", "SharePoint QA", "RFP question"],
    ),
    support_lead(
        lead_id="C10K-086",
        buyer="Maine Community College System",
        email="sfortin@mainecc.edu",
        subject="MCCS IAM Solution RFP - focused UAT support slice",
        source_url="https://www.mccs.me.edu/request-for-proposals/",
        opportunity="Identity and Access Management Solution RFP",
        title="IAM role validation and rollout QA support",
        price=10500,
        segment="IAM rollout support",
        visual="assets/synergy-automation-workflow-visual.png",
        greeting="Hello Scott,",
        opening="I saw the MCCS Identity and Access Management Solution RFP and prepared a focused support packet for role validation, UAT, and rollout readiness.",
        fit="IAM rollout risk often concentrates around role mapping, provisioning/deprovisioning tests, exception handling, and staff handoff.",
        positioning="I can provide a fixed IAM UAT and rollout-readiness package beside the primary identity vendor.",
        boundary="No passwords, tokens, student records, or production credentials should be sent by email; use test tenants, dummy users, or screen-share review.",
        next_step="If a narrow support slice is eligible, I can route the packet through the RFP Coordinator path or to the selected implementation team.",
        caution="Email submission is allowed, but questions deadline passed; keep this as a support component, not a substantive RFP question.",
        deliverables=COMMON_DATA_QA,
        workflow=["Role map", "Access tests", "Exception log", "UAT", "Rollout"],
        packet_path="Email-ready support packet for RFP Coordinator review if eligible.",
        pills=["USD 10,500 fixed", "IAM UAT", "no credentials"],
    ),
    support_lead(
        lead_id="C10K-087",
        buyer="American Battle Monuments Commission",
        email="nerenga@abmc.gov",
        subject="Proposal support slice - 74330226R0044 HRIS",
        source_url="https://www.abmc.gov/rfp/74330226r0044-human-resources-information-system/",
        opportunity="Human Resources Information System RFP 74330226R0044",
        title="HRIS migration and acceptance QA support",
        price=12500,
        segment="HRIS implementation support",
        visual="assets/synergy-automation-workflow-visual.png",
        greeting="Hello Nadine,",
        opening="I saw ABMC's HRIS RFP 74330226R0044 and prepared a focused support packet for migration QA, workflow UAT, and launch-readiness evidence around the main HRIS implementation.",
        fit="The full HRIS response is formal, but a compact migration/UAT support slice can strengthen the implementation evidence if ABMC or a prime uses specialist support.",
        positioning="I can provide a fixed HRIS QA/readiness support slice through the required federal or prime/subcontract channel.",
        boundary="No employee PII, HR records, credentials, or controlled data should be sent by email; use dummy data or an approved secure workspace.",
        next_step="If this type of named support slice is appropriate, please advise whether it should be included directly or through the prime/subcontract path.",
        caution="Federal HRIS. Avoid PII and avoid implying this is the full HRIS proposal.",
        deliverables=COMMON_DATA_QA,
        workflow=["HR fields", "Role tests", "Workflow UAT", "Reports", "Readiness"],
        packet_path="Federal-procurement-aware support note; formal RFP instructions control.",
        pills=["USD 12,500 fixed", "HRIS QA", "no PII"],
    ),
    support_lead(
        lead_id="C10K-088",
        buyer="Friends of Springfield Art Museum",
        email="kate.francis@springfieldmo.gov",
        subject="CRM data migration QA support for museum RFQ",
        source_url="https://sgfmuseum.org/m/newsflash/Home/Detail/228",
        opportunity="CRM RFQ for Friends of Springfield Art Museum / Springfield Art Museum Foundation",
        title="Museum CRM data migration and acceptance QA support",
        price=7500,
        segment="Museum CRM support",
        visual="assets/rrc-salesforce-qa-visual.png",
        greeting="Hi Kate,",
        opening="I saw the CRM RFQ for the Friends of Springfield Art Museum / Springfield Art Museum Foundation and prepared a focused migration QA and acceptance-support packet.",
        fit="The RFQ needs CRM judgment; data mapping, dedupe, import sampling, UAT scripts, and launch evidence are a practical fixed support lane.",
        positioning="I can provide a fixed data migration/UAT support package that helps the CRM team launch with fewer data-quality surprises.",
        boundary="No donor PII, payment records, or private notes should be sent by email; start with field lists, dummy rows, or a secure approved export.",
        next_step="Would a narrow CRM migration QA/support-sidecar be useful for this RFQ, or should I route this only to the selected CRM partner once chosen?",
        caution="Email is allowed. Keep formal, RFQ-specific, and do not claim platform-prime qualifications.",
        deliverables=COMMON_DATA_QA,
        workflow=["Data map", "Dedupe", "Import QA", "Campaign tests", "Handoff"],
        packet_path="RFQ-specific support note, email preferred by the public posting.",
        pills=["USD 7,500 fixed", "CRM migration QA", "donor-data safe"],
    ),
    support_lead(
        lead_id="C10K-089",
        buyer="Town of Hillsborough",
        email="dbelcik@hillsborough.net",
        subject="Data/GIS workflow support question for as-needed services RFP",
        source_url="https://www.hillsborough.net/207/Request-for-Proposals",
        opportunity="As-needed consulting and engineering services RFP",
        title="GIS/data workflow QA and deliverable support slice",
        price=6500,
        segment="Municipal data support",
        visual="assets/harford-routing-qa-visual.png",
        greeting="Hello David,",
        opening="I saw the Town of Hillsborough as-needed consulting and engineering services RFP and prepared a narrow data/GIS workflow support packet that could sit beside the licensed consultant team.",
        fit="The support lane is data, GIS, issue tracking, public-facing deliverable QA, and handoff evidence beside licensed professionals.",
        positioning="I can provide fixed data, GIS, and deliverable QA support beside the town's selected consultant or task-order team.",
        boundary="No licensed engineering, survey, planning certification, or sealed deliverable is included; this is data/workflow QA and documentation support.",
        next_step="Could you confirm whether a narrow data/GIS workflow support note is useful for this RFP, or should it be routed through the selected consultant team?",
        caution="Do not imply engineering credentials. Email is appropriate only as a support/teaming question.",
        deliverables=COMMON_DATA_QA,
        workflow=["Data inventory", "Map QA", "Issue log", "Report check", "Handoff"],
        packet_path="Eligibility/selected-consultant support note; no licensed-service claim.",
        pills=["USD 6,500 fixed", "GIS/data QA", "no licensed claim"],
    ),
    support_lead(
        lead_id="C10K-090",
        buyer="Society of St. Vincent de Paul Cincinnati",
        email="ajones@svdpcincinnati.org",
        cc="andy.ey@svdpcincinnati.org",
        subject="Website RFP QA/support slice for SVDP Cincinnati",
        source_url="https://www.svdpcincinnati.org/wp-content/uploads/2026/04/RFP-for-St.-Vincent-de-Paul-Website.pdf",
        opportunity="Website and digital presence RFP",
        title="Website launch QA, accessibility, and donor-path support",
        price=6800,
        segment="Nonprofit website support",
        visual="assets/baxter-website-qa-visual.png",
        greeting="Hi Kelsey,",
        opening="I saw SVDP Cincinnati's website RFP and prepared a focused launch-QA/support packet for accessibility, donor/volunteer paths, content migration checks, and staff handoff.",
        fit="The RFP is mission-critical: donor trust, volunteer conversion, service navigation, and accessible content all need structured QA before launch.",
        positioning="I can provide a fixed QA/readiness package for SVDP or the selected web vendor without taking over the full redesign.",
        boundary="No donor, client, volunteer, or payment data should be sent by email; use public pages, dummy form submissions, and redacted examples.",
        next_step="If useful, I can tailor this as a support attachment for the RFP response or route it to the selected website partner.",
        caution="Direct email is available. Local-firm preference exists, so keep this as support-sidecar unless bidding as prime.",
        deliverables=COMMON_WEB_QA,
        workflow=["Path map", "Form tests", "Access QA", "Content QA", "Launch pack"],
        packet_path="Email-ready support packet for RFP review or selected-vendor routing.",
        pills=["USD 6,800 fixed", "donor-path QA", "accessibility"],
    ),
    support_lead(
        lead_id="C10K-091",
        buyer="Northumberland Humane Society",
        email="campaigndirector@northumberlandhs.com",
        subject="Website RFP launch QA and donation/adoption workflow support",
        source_url="https://www.northumberlandhs.com/s/Website-Development_RFP_V1-1.pdf",
        opportunity="Website development RFP",
        title="Donation, adoption, and campaign website QA support",
        price=4800,
        segment="Animal welfare website support",
        visual="assets/baxter-website-qa-visual.png",
        greeting="Hello Northumberland Humane Society Campaign Team,",
        opening="I saw the NHS website development RFP and prepared a focused support packet for adoption/donation workflows, accessibility, integration checks, and launch-readiness evidence.",
        fit="The website needs to support adoption interest, campaign storytelling, CanadaHelps, DonorPerfect, Mailchimp, mobile access, and accessible public content.",
        positioning="I can provide a compact QA/readiness package beside the selected web partner or as a small fixed support scope.",
        boundary="No donor, adopter, volunteer, or animal medical records should be sent by email; use public pages, dummy forms, and redacted screenshots.",
        next_step="If helpful, I can route the support packet to the right person or adapt it for the selected vendor once chosen.",
        caution="Ontario/local vendor preference. Keep as support-sidecar and do not imply local status.",
        deliverables=COMMON_WEB_QA,
        workflow=["Adoption path", "Donation tests", "Email checks", "Access QA", "Handoff"],
        packet_path="Email-ready support-sidecar for RFP review or selected-vendor routing.",
        pills=["USD 4,800 fixed", "adoption workflow", "donor-data safe"],
    ),
    support_lead(
        lead_id="C10K-092",
        buyer="Institute of International Education",
        email="Arowland@iie.org",
        subject="Fulbright Scholar Program Website Maintenance - support slice",
        source_url="https://www.iie.org/get-involved/procurement-subaward-and-consultant-opportunities/solicitations-for-goods-and-services/",
        opportunity="RFP 05062026/AK Fulbright Scholar Program Website Development and Maintenance",
        title="Fulbright Scholar website maintenance QA and accessibility support",
        price=12500,
        segment="Education website maintenance support",
        visual="assets/hiawatha-school-workflow-visual.png",
        greeting="Hello Alexa,",
        opening="I saw IIE's RFP 05062026/AK for Fulbright Scholar Program Website Development and Maintenance and prepared a focused support packet for maintenance QA, accessibility checks, broken-link/form testing, and handoff evidence.",
        fit="The RFP calls for website maintenance, enhancement, quarterly checks, broken-link/form testing, analytics reporting, access-controlled content, and responsiveness standards.",
        positioning="I can provide a fixed QA/readiness support slice that complements a full-service website maintenance provider.",
        boundary="No applicant, program participant, or protected account data should be sent by email; use public pages, dummy forms, and approved test accounts only.",
        next_step="If a named support resource is acceptable, I can include this as a small fixed scope or route it to the full-service provider path.",
        caution="Full-service RFP. Keep as support slice unless user can submit full qualified proposal.",
        deliverables=COMMON_WEB_QA,
        workflow=["Site crawl", "Form tests", "Access paths", "Quarterly QA", "Report pack"],
        packet_path="Email-ready support packet; IIE's RFP instructions and attachment limits control.",
        pills=["USD 12,500 fixed", "maintenance QA", "Fulbright site"],
    ),
    support_lead(
        lead_id="C10K-093",
        buyer="THRIVE Victoria",
        email="development@thrivevictoria.org",
        subject="Website Designer RFP - launch QA and campaign workflow support",
        source_url="https://thrivevictoria.org/jobs/website-designer/",
        opportunity="Website Designer RFP",
        title="Youth-services website QA and campaign-readiness support",
        price=7500,
        segment="Nonprofit campaign website support",
        visual="assets/hiawatha-school-workflow-visual.png",
        greeting="Hello THRIVE Development Team,",
        opening="I saw THRIVE's Website Designer RFP and prepared a focused support packet for campaign readiness, donor/funder paths, youth-and-family service navigation, accessibility, and launch QA.",
        fit="The RFP has clear dual-user journeys: donors/funders and clients/youth/families. That makes structured path testing, accessibility, privacy-safe forms, and CMS handoff especially important.",
        positioning="I can provide a bounded QA/readiness support package beside the chosen designer/developer or as a small fixed add-on.",
        boundary="No client, youth, family, donor, or private service data should be sent by email; use public content, dummy forms, and redacted examples.",
        next_step="If useful, I can provide this as a support slice around the main website proposal or route it to the selected vendor once chosen.",
        caution="Direct email proposal path. Canadian nonprofit; quote in USD for Codex10k tracking but buyer budget is CAD.",
        deliverables=COMMON_WEB_QA,
        workflow=["User journeys", "Campaign paths", "Service forms", "Access QA", "CMS handoff"],
        packet_path="Email-ready support-sidecar for RFP review or selected-vendor routing.",
        pills=["USD 7,500 fixed", "campaign QA", "privacy-safe"],
    ),
]

followups = [
    ("C10K-094", "Baxter State Park Authority", "nava.tabak@baxterstatepark.org", "", "19e10a5e7c318c9b", "baxter-website-launch-qa-sidecar.html", "outputs/codex10k/baxter_website_launch_qa_sidecar_proposal.pdf", "Baxter ADA/migration launch QA follow-up", 8500, "State park website support", "assets/baxter-website-qa-visual.png"),
    ("C10K-095", "Harford County Public Schools", "sara.rowe@hcps.org", "", "19e10c2baf1299e8", "harford-routing-data-qa-sidecar.html", "outputs/codex10k/harford_routing_data_qa_support_question.pdf", "Harford routing data QA follow-up", 9500, "K-12 routing data support", "assets/harford-routing-qa-visual.png"),
    ("C10K-096", "Revenue Authority of Prince George's County", "RVA-PMS.RFP@co.pg.md.us", "", "19e10e01ea3147ae", "pgc-parking-data-qa-sidecar.html", "outputs/codex10k/pgc_parking_data_qa_support_slice.pdf", "Parking PMS migration QA follow-up", 14500, "Parking data support", "assets/pgc-parking-data-qa-visual.png"),
    ("C10K-097", "Napa Valley Transportation Authority", "procurements@nvta.ca.gov", "rcoombs@nvta.ca.gov", "19e101890b095ee2", "nvta-ada-qa-sidecar.html", "outputs/codex10k/nvta_ada_qa_sidecar_quote.pdf", "NVTA ADA website QA follow-up", 4800, "ADA website QA support", "assets/nvta-ada-qa-visual.png"),
    ("C10K-098", "Town of Duck", "knickens@ducknc.gov", "", "19e10294ab3b5ab5", "duck-ada-launch-qa-sidecar.html", "outputs/codex10k/town_of_duck_launch_qa_sidecar_proposal.pdf", "Town of Duck launch QA follow-up", 6800, "Municipal website launch support", "assets/baxter-website-qa-visual.png"),
    ("C10K-099", "Ely Area Tourism Bureau", "jess@rootbeerlady.com", "", "19e1037e9f166d0a", "ely-migration-qa-sidecar.html", "outputs/codex10k/ely_migration_qa_launch_readiness_proposal.pdf", "Ely tourism migration QA follow-up", 12500, "Tourism website migration support", "assets/baxter-website-qa-visual.png"),
    ("C10K-100", "Hiawatha Academies", "kgroves@hiawathaacademies.org", "", "19e104c1b35de655", "hiawatha-school-website-qa-sidecar.html", "outputs/codex10k/hiawatha_school_website_qa_sidecar_proposal.pdf", "Hiawatha multilingual website QA follow-up", 12000, "School website QA support", "assets/hiawatha-school-workflow-visual.png"),
    ("C10K-101", "3D Walkabout", "tim@3dwalkabout.com.au", "", "19e0feb8882b174a", "3dwalkabout-hubspot-clickup.html", "", "3D Walkabout HubSpot-ClickUp sprint follow-up", 1800, "CRM automation support", "assets/synergy-automation-workflow-visual.png"),
    ("C10K-102", "SnipeAgent", "contact@snipeagent.ai", "", "19e0ffab0e946f49", "snipeagent-sms-automation.html", "", "SnipeAgent architecture pass follow-up", 400, "SMS automation architecture support", "assets/snipeagent-sms-workflow-visual.png"),
    ("C10K-103", "Chek Creative", "hello@chekcreative.com", "", "19e10093fb4ce954", "chek-automation-partner-pilot.html", "", "Chek Creative automation pilot follow-up", 1200, "Automation agency support", "assets/synergy-automation-workflow-visual.png"),
]

for lead_id, buyer, email, cc, reply_id, page, pdf, title, price, segment, visual in followups:
    leads.append(
        support_lead(
            lead_id=lead_id,
            buyer=buyer,
            email=email,
            cc=cc,
            reply_message_id=reply_id,
            subject=f"Following up: {title}",
            source_url=f"https://anonymusk7.github.io/codex10k-workflow-recovery/{page}",
            opportunity=title,
            title=title,
            price=price,
            segment=segment,
            visual=visual,
            greeting=f"Hello {buyer} team,",
            opening="I am following up on the support packet I sent earlier. I kept this as a small fixed scope so it can be approved quickly if the timing is useful.",
            fit="This is already scoped around the buyer's public RFP, public support request, or previously sent packet.",
            positioning="I can keep the first milestone tight: confirm the workflow, work from approved samples or public/staging material, produce acceptance evidence, and hand off the exact next fixes.",
            boundary="No credentials, private records, payment data, or production secrets should be sent by email; start with approved samples, public URLs, redacted screenshots, or a secure workspace.",
            next_step="If this is worth considering, the fastest next step is a short approval note with the right billing contact and any procurement path I should follow.",
            email_next_step="If this is useful, a simple reply with the right billing/procurement contact is enough and I will convert the scoped packet into the correct payment or vendor path.",
            caution="Follow-up draft only. Do not send immediately unless user wants a manual follow-up cadence.",
            deliverables=COMMON_WEB_QA if "website" in segment.lower() or "ada" in segment.lower() or "tourism" in segment.lower() else COMMON_DATA_QA,
            workflow=["Confirm scope", "Sample review", "QA run", "Retest", "Handoff"],
            exclusions="This is not a replacement for the main vendor, legal certification, hosting contract, or ongoing managed service unless separately agreed.",
            packet_path="Follow-up to the previously sent support packet; can move to billing or procurement if useful.",
            pills=[f"USD {price:,} fixed", "scoped packet", "approval path"],
        )
    )

OUT.write_text(json.dumps(leads, indent=2) + "\n")
print(f"Wrote {len(leads)} leads to {OUT.relative_to(ROOT)}")
